### ISSUE TITLE
TypeError: this.optios is not a function

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic#117]
Seit einiger Zeit bekomme ich laufend folgende Fehlermeldung - ist dies ein bug?

TypeError: this.optios is not a function
    at HmipSmi55.init (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices/hmip-smi55.js:15:18)
    at new Accessory (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices/lib/accessory.js:77:18)
    at new HmipSmi55 (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices/hmip-smi55.js:3:18)
    at RedMaticHomeKitHomematicDevices.createHomematicDevice (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-devices.js:129:28)
    at Object.keys.forEach.address (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-devices.js:95:30)
    at Array.forEach (<anonymous>)
    at RedMaticHomeKitHomematicDevices.publishDevices (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/nodes/redmatic-homekit-homematic-devices.js:82:48)
    at RedMaticHomeKitHomematicDevices.setStatus (/usr/local/addo...

**Comment by drMaxxi** [comment]
Zusätzliche aktuelle Fehlermeldungen sind:

createHomematicDevice Exception 1. Stock Bürotaster hmip-smi55

Error: binrpc server close timeout

Ich poste diese sicherheitshalber da ich nicht weiss ob sie mit dem oben genannten Bug zu tun haben. Sie erscheinen in den Debug Messages immer vor der oben beschriebenen Nachricht.
