### ISSUE TITLE
2.0.0 startet nicht - Error loading settings file

### ISSUE THREAD

**Issue by Tscherno** [HM-RedMatic/RedMatic#134]
```
Jan 12 22:58:55 homematic daemon.info redmatic: Starting Node-RED
Jan 12 22:58:57 homematic daemon.err node-red: Error loading settings file: /usr/local/addons/redmatic/lib/settings.js
Jan 12 22:58:57 homematic daemon.err node-red: TypeError: Cannot read property 'default' of undefined
Jan 12 22:58:57 homematic daemon.err node-red:     at Object.<anonymous> (/usr/local/addons/redmatic/lib/settings.js:42:29)
Jan 12 22:58:57 homematic daemon.err node-red:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Jan 12 22:58:57 homematic daemon.err node-red:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Jan 12 22:58:57 homematic daemon.err node-red:     at Module.load (internal/modules/cjs/loader.js:599:32)
Jan 12 22:58:57 homematic daemon.err node-red:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Jan 12 22:58:57 homematic daemon.err node-red:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Jan 12 22:58:57 homematic daemon.err node-red:     at Module.require (internal/modules/cjs/loader.js:637:17)
Jan 12 22:58:57 homematic daemon.err node-red:     at require (internal/modules/cjs/helpers.js:22:18)
Jan 12 22:58:57 homematic daemon.err node-red:     at Object.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/node-red/red.js:115:20)
Jan 12 22:58:57 homematic daemon.err node-red:     at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by Tscherno** [comment]
Problem gelöst: Nachdem ich das Loglevel auf Trace geändert habe (damit wurde wohl die Konfiguration neu geschrieben) läuft es wieder.

**Comment by habeck76** [comment]
Bei mir genau das gleiche! Erst Fehler 1. Auf Trace geändert, dann Fehler 2.

**Comment by juppjuppsen** [comment]
Kann ich leider so bestätigen

**Comment by habeck76** [comment]
Komplett deinstallieren und neu installieren. Dann läuft es.

**Comment by juppjuppsen** [comment]
Und meine Nodes bleiben bei der Deinstallation erhalten?

**Comment by hobbyquaker** [comment]
Beim Deinstallieren gehen die Flows verloren, die müsste man vorher händisch sichern. Bin aber schon an einem Hotfix dran.

**Comment by hobbyquaker** [comment]
Hoffe das mit v2.0.1 aus der Welt geschafft zu haben.

**Comment by Tscherno** [comment]
Vielleicht nicht der richtige Thread, aber passt zum Thema: Was ist der beste Weg alle Flows zu sichern?

**Comment by hobbyquaker** [comment]
Für eine manuelle Sicherung sind folgende Dateien relevant:

* `/usr/local/addons/redmatic/var/flows.json`
* `/usr/local/addons/redmatic/var/flows_cred.json`
* `/usr/local/addons/redmatic/var/homekit/*`
* `/usr/local/addons/redmatic/etc/settings.json`
* `/usr/local/addons/redmatic/etc/credentials.key`

Falls das Node-RED Projects-Feature aktiviert der Ordner
* `/usr/local/addons/redmatic/var/projects` 

Das alles steckt auch mit im CCU Backup.

**Comment by juppjuppsen** [comment]
> Ohje, da bin ich erstmal ratlos warum das immer noch auftritt :(
> Bitte lösche mal die Datei `/usr/local/addons/redmatic/etc/settings.json` und versuche dann noch mal Node-RED zu starten.

Das führt dann zu folgenden Meldungen:

```
Jan 13 10:27:37 ZentraleHausautomatisierung daemon.info node-red[2299]: Dashboard version 2.13.0 started at /addons/red/ui
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.info node-red[2299]: node-red-contrib-ccu version: 1.10.11
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.info node-red[2299]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.err node-red[2299]: Failed to start server:
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.err node-red[2299]: Error: Error loading context store: Error: Context store 'default' missing 'module' option
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.err node-red[2299]:     at /usr/local/addons/redmatic/lib/node_modules/node-red/red/runtime/nodes/context/index.js:175:15
Jan 13 10:27:39 ZentraleHausautomatisierung daemon.err node-red[2299]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Jan 13 10:34:21 ZentraleHausautomatisierung daemon.info redmatic: RedMatic v2.0.1 (c) Sebastian Raff https://github.com/HM-RedMatic/RedMatic
Jan 13 10:34:21 ZentraleHausautomatisierung daemon.info redmatic: Starting Node-RED
Jan 13 10:34:23 ZentraleHausautomatisierung daemon.err node-red: Error loading settings file: /usr/local/addons/redmatic/lib/settings.js
Jan 13 10:34:23 ZentraleHausautomatisierung daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/etc/settings.json'
Jan 13 10:34:44 ZentraleHausautomatisierung daemon.info redmatic: RedMatic v2.0.1 (c) Sebastian Raff https://github.com/HM-RedMatic/RedMatic
Jan 13 10:34:44 ZentraleHausautomatisierung daemon.info redmatic: Starting Node-RED
Jan 13 10:34:46 ZentraleHausautomatisierung daemon.err node-red: Error loading settings file: /usr/local/addons/redmatic/lib/settings.js
Jan 13 10:34:46 ZentraleHausautomatisierung daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/etc/settings.json'
Jan 13 10:34:53 ZentraleHausautomatisierung daemon.info redmatic: RedMatic v2.0.1 (c) Sebastian Raff https://github.com/HM-RedMatic/RedMatic
Jan 13 10:34:53 ZentraleHausautomatisierung daemon.info redmatic: Starting Node-RED
Jan 13 10:34:55 ZentraleHausautomatisierung daemon.err node-red: Error loading settings file: /usr/local/addons/redmatic/lib/settings.js
Jan 13 10:34:55 ZentraleHausautomatisierung daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/etc/settings.json'
cat: can't open '/var/log/messages.0': No such file or directory
```

Folgend noch der Inhalt meiner settings.json:

```
{
  "uiPort": 1880,
  "uiHost": "127.0.0.1",
  "flowFile": "flows.json",
  "userDir": "/usr/local/addons/redmatic/var",
  "httpRoot": "/addons/red",
  "logging": {
    "ain": {
      "level": "debug",
      "metrics": false,
      "audit": false
    }
  },
  "contextStorage": {
    "default": {
      "module": "localfilesystem"
    }
  },
  "restartOnCrash": 0,
  "httpNodeAuth": {
    "user": "Admin",
    "pass": "<Passwort>"
  }
}
```

**Comment by hobbyquaker** [comment]
Args. Sorry für die Umstände. Ich bin aber verhalten optimistisch dass die v2.0.2 das nun endgültig behebt.

**Comment by juppjuppsen** [comment]
> 
> 
> Args. Sorry für die Umstände. Ich bin aber verhalten optimistisch dass die v2.0.2 das nun endgültig behebt.

Kein Problem - das AddOn ist der Hammer - ich denke dir wird diesbezüglich alles verziehen :-).

Nachdem ich die Datei settings.js mit deinem letzten commit ersetzt habe läuft es nun.

Danke!
