### ISSUE TITLE
Install failed: node-red-contrib-mysensors

### ISSUE THREAD

**Issue by tgmann** [HM-RedMatic/RedMatic#154]
Hallo,

ich habe versucht, die Nodes für MySensors nachzuinstallieren, Keider schlägt auch dies beim Nachladen von Binärpaketen fehl. Wenn ich irgendiowe zur Lösung des Problems beitragen kann, dann gern.

```

{
   "ccu": {
      "VERSION": "3.41.11",
      "PRODUCT": "ccu3",
      "PLATFORM": "rpi3"
   },
   "redmatic": "2.7.0",
   "nodejs": "10.15.1",
   "ain2": "3.0.0",
   "node-red": "0.19.5",
   "node-red-contrib-modbus": "4.1.1",
   "node-red-contrib-smartmeter": "0.2.0",
   "node-red-node-serialport": "0.7.0",
   "node-red-node-sqlite": "0.3.6",
   "npm": "6.8.0",
   "redmatic-homekit": "1.9.0",
   "node-red-contrib-ccu": "1.16.1",
   "node-red-contrib-combine": "1.6.2",
   "node-red-contrib-mqtt-json": "1.0.1",
   "node-red-contrib-sun-position": "0.2.2",
   "node-red-contrib-telegrambot": "5.2.1",
   "node-red-dashboard": "2.13.2",
   "node-red-node-email": "1.2.0",
   "node-red-node-rbe": "0.2.4",
   "redmatic-led": "1.0.0",
   "redmatic-webapp": "0.2.1"
}
Feb 18 22:44:17 ccu3-webui daemon.info redmatic: RedMatic v2.7.0 (c) Sebastian Raff https://github.com/HM-RedMatic/RedMatic
Feb 18 22:44:17 ccu3-webui daemon.info redmatic: Starting Node-RED
Feb 18 22:44:22 ccu3-webui daemon.info node-red[880]: Welcome to Node-RED
Feb 18 22:44:22 ccu3-webui daemon.info node-red[880]: ===================
Feb 18 22:44:22 ccu3-webui daemon.info node-red[880]: Node-RED version: v0.19.5
Feb 18 22:44:22 ccu3-webui daemon.info node-red[880]: Node.js  version: v10.15.1
Feb 18 22:44:22 ccu3-webui daemon.info node-red[880]: Linux 4.14.34 arm LE
Feb 18 22:44:22 ccu3-webui daemon.err node-red: (node:880) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Feb 18 22:44:23 ccu3-webui daemon.info node-red[880]: Loading palette nodes
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-node-rbe 0.2.4
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-node-rbe
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-ccu 1.16.1
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-mqtt-json 1.0.1
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-contrib-mqtt-json
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-sun-position 0.2.2
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-contrib-sun-position
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-telegrambot 5.2.1
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-contrib-telegrambot
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-dashboard 2.13.2
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-dashboard
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-node-email 1.2.0
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-node-email
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-combine 1.6.2
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/node-red-contrib-combine
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: redmatic-led 1.0.0
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/redmatic-led
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: redmatic-webapp 0.2.1
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/var/node_modules/redmatic-webapp
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-modbus 4.1.1
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-modbus
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-contrib-smartmeter 0.2.0
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-smartmeter
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-node-serialport 0.7.0
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/lib/node_modules/node-red-node-serialport
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: node-red-node-sqlite 0.3.6
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/lib/node_modules/node-red-node-sqlite
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]: Module: redmatic-homekit 1.9.0
Feb 18 22:44:24 ccu3-webui daemon.debug node-red[880]:         /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit
Feb 18 22:44:33 ccu3-webui daemon.info node-red[880]: Dashboard version 2.13.2 started at /addons/red/ui
Feb 18 22:44:36 ccu3-webui daemon.info node-red[880]: node-red-contrib-ccu version: 1.16.1
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: Context store  : 'default' [module=memory]
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: Context store  : 'file' [module=localfilesystem]
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: User directory : /usr/local/addons/redmatic/var
Feb 18 22:44:37 ccu3-webui daemon.warn node-red[880]: Projects disabled : editorTheme.projects.enabled=false
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: Flows file     : /usr/local/addons/redmatic/var/flows.json
Feb 18 22:44:37 ccu3-webui daemon.info node-red[880]: Server now running at http://127.0.0.1:1880/addons/red/
...
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: Installation of module node-red-contrib-mysensors failed:
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: ------------------------------------------
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: > sqlite3@4.0.6 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: > node-pre-gyp install --fallback-to-build
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp WARN Using request for node-pre-gyp https download 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v64-linux-arm.tar.gz 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! configure error 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at F (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:68:16)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at E (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:80:29)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/which/which.js:89:16
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/index.js:42:5
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! System Linux 4.14.34
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! node -v v10.15.1
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! node-gyp -v v3.8.0
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: gyp ERR! not ok 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! build error 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! System Linux 4.14.34
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! command "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! cwd /usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! node -v v10.15.1
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! node-pre-gyp -v v0.11.0
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: node-pre-gyp ERR! not ok 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: Failed to execute '/usr/local/addons/redmatic/bin/node /usr/local/addons/redmatic/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/addons/redmatic/var/node_modules/node-red-contrib-mysensors/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm WARN node-red-project@0.0.1 No repository field.
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm WARN node-red-project@0.0.1 No license field.
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! code ELIFECYCLE
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! errno 1
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! Exit status 1
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! 
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! Failed at the sqlite3@4.0.6 install script.
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR! A complete log of this run can be found in:
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: npm ERR!     /usr/local/addons/redmatic/npm-cache/_logs/2019-02-18T21_45_56_228Z-debug.log
Feb 18 22:45:56 ccu3-webui daemon.warn node-red[880]: ------------------------------------------



```

**Comment by hobbyquaker** [comment]
ich nehms mit ins nächste Release auf

**Comment by tgmann** [comment]
Vielen Dank für die schnelle Hilfe.

**Comment by hobbyquaker** [comment]
@tgmann steckt nun in RedMatic 2.8.0 mit drin. Bitte gib Bescheid ob es funktioniert.

**Comment by tgmann** [comment]
@hobbyquaker Es scheint grundsätzlich zu funktionieren. Die Benutzung der Nodes ist nicht ganz trivial, ich muss mich noch etwas reinfuchsen. Aber bis jetzt sieht's gut aus. Danke nochmal.
